# Generated by Django 2.0.5 on 2019-07-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_phishing_model_sendmail_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmail_model',
            name='decsription',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendmail_model',
            name='file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendmail_model',
            name='file_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
