# Generated by Django 2.0.5 on 2019-07-23 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20190723_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingThread_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=500)),
                ('atk', models.CharField(max_length=100)),
                ('usid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.UserRegister_Model')),
            ],
        ),
    ]
