# Generated by Django 2.0.5 on 2019-07-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_feedbackmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmail_model',
            name='decsription',
        ),
        migrations.RemoveField(
            model_name='sendmail_model',
            name='file',
        ),
        migrations.RemoveField(
            model_name='sendmail_model',
            name='file_name',
        ),
    ]
