# Generated by Django 2.0.5 on 2019-07-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20190729_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendMail_Model',
            new_name='SendMailModel',
        ),
    ]
