# Generated by Django 2.0.5 on 2019-07-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam_category', models.CharField(max_length=250)),
                ('spam_list', models.CharField(max_length=250)),
            ],
        ),
    ]
